### PR TITLE
Backport multisig fixes to voting contracts

### LINKED ISSUE #176: Backport multisig fixes to voting contracts
Similar to https://github.com/confio/tgrade-contracts/issues/523.

Recently a couple of multisig bugs were fixed in cw-plus:

- https://github.com/CosmWasm/cw-plus/pull/783
- https://github.com/CosmWasm/cw-plus/pull/784

Implement these fixes in the PoE voting contracts (`tgrade-community-pool` and `tgrade-validator-voting`).

### PR DESCRIPTION
**Pull request by 0xFable**
Fixes #176 
Backported the logic to the package level instead of implementing it in each of the two contracts. If this was not the right approach let me know. 
Instead of porting the unit test I made it into a multitest.

### CODE REVIEW

File: packages/voting-contract/src/lib.rs [hunk 1]
```diff
@@ -157,10 +162,11 @@ where
     P: Serialize + DeserializeOwned,
 {
     let mut proposal = proposals::<P>().load(storage, proposal_id)?;
-
+    // Update Status
+    proposal.update_status(&env.block);
     // We allow execution even after the proposal "expiration" as long as all votes come in before
     // that point. If it was approved on time, it can be executed any time.
-    if proposal.current_status(&env.block) != Status::Passed {
+    if proposal.status != Status::Passed {
```
Comment (ueco-jb) [inline packages/voting-contract/src/lib.rs:169]: This is redundant, since previous call `current_status` is called by `update_status` anyway.

File: packages/voting-contract/src/multitest/voting.rs [hunk 2]
```diff
@@ -368,5 +368,53 @@ fn expired_proposals_cannot_be_voted_on() {
...
+        .with_member("bob", 2)
+        .with_rules(rules.clone())
+        .build();
+
+    // Create proposal with 1 voting power
+    let response = suite.propose("alice", "cool proposal", "proposal").unwrap();
+    let proposal_id: u64 = get_proposal_id(&response).unwrap();
+
+    // Bob can vote on the proposal
+    let _ = suite.vote("bob", proposal_id, Vote::Yes).unwrap();
```
Comment (ueco-jb) [inline packages/voting-contract/src/multitest/voting.rs:392]:
```suggestion
    suite.vote("bob", proposal_id, Vote::Yes).unwrap();
```

File: packages/voting-contract/src/multitest/voting.rs [hunk 3]
```diff
@@ -368,5 +368,53 @@ fn expired_proposals_cannot_be_voted_on() {
...
+
+    // Verify proposal is now passed
+    let prop = suite.query_proposal(proposal_id).unwrap();
+    assert_eq!(prop.status, Status::Passed);
+
+    // Alice can't vote on the proposal
+    let err = suite.vote("alice", proposal_id, Vote::Yes).unwrap_err();
+
+    // proposal that is open and expired is rejected
+    assert_eq!(ContractError::Expired {}, err.downcast().unwrap());
```
Comment (ueco-jb) [inline packages/voting-contract/src/multitest/voting.rs:405]: That comment is incorrect. 
If the proposal was `Rejected`, it couldn't be closed: https://github.com/confio/poe-contracts/blob/main/packages/voting-contract/src/lib.rs#L199-L201
Can you revisit logic and adjust comments?

File: packages/voting-contract/src/multitest/voting.rs [hunk 4]
```diff
@@ -368,5 +368,53 @@ fn expired_proposals_cannot_be_voted_on() {
...
+
+    // Move time forward more so proposal expires
+    suite.app.advance_seconds(prop.expires.time().seconds());
+
+    // But she can execute the proposal
+    let _ = suite.execute_proposal("alice", proposal_id).unwrap();
```
Comment (ueco-jb) [inline packages/voting-contract/src/multitest/voting.rs:411]:
```suggestion
    suite.execute_proposal("alice", proposal_id).unwrap();
```

**Review by ueco-jb — COMMENTED** [review]
Logic is correct, but please adjust comments on test.

File: packages/voting-contract/src/lib.rs (hunk 1 above)
Comment (0xFable) [reply packages/voting-contract/src/lib.rs]: I reverted back 169 to the way it was but curious would it not be more redundant to to keep it that way as `proposal.status` uses the result of the first `current_status` call rather than what I went back to which is calling it again?

**Review by ueco-jb — APPROVED** [review]
LGTM

File: packages/voting-contract/src/lib.rs [hunk 5]
```diff
@@ -157,7 +162,8 @@ where
     P: Serialize + DeserializeOwned,
 {
     let mut proposal = proposals::<P>().load(storage, proposal_id)?;
-
+    // Update Status
+    proposal.update_status(&env.block);
```
Comment (maurolacy) [inline packages/voting-contract/src/lib.rs:166]: This is not needed. Status will be updated below, and the check is already using `current_status`.

**Review by maurolacy — APPROVED** [review]
LGTM.

File: packages/voting-contract/src/lib.rs (hunk 5 above)
Comment (maurolacy) [reply packages/voting-contract/src/lib.rs:166]: Funny how we have two or three different implementations / variations of the same logic.

It will be good to move this `voting-contract` package to cw-plus at some point, and change all multisigs (cw-plus, poe-contracts, and Tgrade-contracts) to use it.

Comment (maurolacy) [reply packages/voting-contract/src/lib.rs:166]: Created See https://github.com/confio/poe-contracts/issues/194 to track that effort.
