### PR TITLE
Voting Contract: vote and close uses current status

### LINKED ISSUE #55: [voting-contract] More status issues
Found a couple more issues relates to proposal status, while backporting the current fixes in #14 
and #16 to [cw-plus multisig contracts](https://github.com/CosmWasm/cw-plus/issues/630):

- `vote` checks the `status` field directly (instead of using the `current_status` helper).
- `close` checks the `status` field directly (instead of using the `current_status` helper).

When changing these, some tests fails.

### PR DESCRIPTION
**Pull request by ueco-jb**
closes #55

Closing and voting methods now use `current_status()` helper, which underneath can update status to Rejected.
Because of that, first time closing a proposal that should be rejected could fail, because there was check in place to see, if status... is not already rejected.
To mitigate that, I used simple solution with saving status before closing, in order to detect if someone tries to close proposal first of 1+nth time. 

~~I added extra `.save()` under each update status, since in case of early exit status update would be lost.~~ So that doesn't work, and I don't like it. :)
So someone tries to vote on proposal, `update_status()` changes state to `Rejected` and vote is rejected, but then validator queries the proposal and sees that `status` was the same as before - probably just Open.

I didn't change anything in `state.rs` file, simply moved `impl Proposal` so that it would be directly under its structure, instead on bottom of file for some reason.

### CODE REVIEW

File: packages/voting-contract/src/lib.rs [hunk 1]
```diff
@@ -116,12 +116,14 @@ where
 {
     // ensure proposal exists and can be voted on
     let mut prop = proposals().load(deps.storage, proposal_id)?;
-    if prop.status != Status::Open {
+    prop.update_status(&env.block);
+    proposals::<P>().save(deps.storage, proposal_id, &prop)?;
```
Comment (uint) [inline packages/voting-contract/src/lib.rs:120]: So if I understand this correctly, you save here so that the status is updated even if an error is returned from the fn in the next lines?

Here's the thing. This save doesn't write to the storage directly, but to a cache. All such changes are committed to persistent storage later if the fn succeeds and discarded if the fn returns an error. So basically - this save will achieve nothing when there's an error returned.

I suggest just having one proposal save in the entire function.

File: packages/voting-contract/src/lib.rs [hunk 2]
```diff
@@ -197,20 +199,34 @@ where
 {
     // anyone can trigger this if the vote passed
 
-    let mut prop = proposals::<P>().load(deps.storage, proposal_id)?;
-    if [Status::Executed, Status::Rejected, Status::Passed]
+    let mut prop = proposals().load(deps.storage, proposal_id)?;
+    let previous_status = prop.status;
+    prop.update_status(&env.block);
+    proposals::<P>().save(deps.storage, proposal_id, &prop)?;
```
Comment (uint) [inline packages/voting-contract/src/lib.rs:205]: Same as with `vote` - this is unnecessary.

File: packages/voting-contract/src/lib.rs [hunk 3]
```diff
@@ -197,20 +199,34 @@ where
...
 
-    // set it to failed
-    prop.status = Status::Rejected;
-    proposals::<P>().save(deps.storage, proposal_id, &prop)?;
+    // Two scenarios:
+    // 1) any status -> rejected (update_status changed it)
+    // 2) proposal was already rejected (double close)
+    // To differentiate those, we need to compare current status with previous one
+    // If that condition is false, then it is first time closing this proposal
+    if prop.status == Status::Rejected && previous_status == Status::Rejected {
```
Comment (uint) [inline packages/voting-contract/src/lib.rs:222]: I think you might as well just check the status at the beginning of the fn and return `ContractError::Rejected` if the status was already `Rejected`, then update it, and so on. Should end up with simpler logic.

**Review by uint — DISMISSED** [review]

**Comment by uint** [comment]
Overall: really awesome you caught these problems, but I have some comments!

> I added extra `.save()` under each update status, since in case of early exit status update would be lost. So someone tries to vote on proposal, `update_status()` changes state to `Rejected` and vote is rejected, but then validator queries the proposal and sees that `status` was the same as before.

Got a test for this?

> I didn't change anything in `state.rs` file, simply moved `impl Proposal` so that it would be directly under its structure, instead on bottom of file for some reason.

:ok_hand:

File: packages/voting-contract/src/multitest/early_end.rs [hunk 4]
```diff
@@ -35,7 +35,6 @@ fn yes_vote_can_pass_proposal_early() {
 fn passed_on_expiration_can_be_executed() {
     let rules = RulesBuilder::new()
         .with_threshold(Decimal::percent(50))
-        .with_quorum(Decimal::percent(20))
```
[the remark this answers is not in the document]
Comment (hashedone) [reply packages/voting-contract/src/multitest/early_end.rs:38]: Yep, I agree with @uint here. My bad I didn't include quorum on other tests as I didn't find it critical for flow, but didn't notice it is 1% by default (I was somehow assuming it is 50% - doesn't matter). But in general any data which is relevant to the test for reading should be visible (that is why I very like to add even things like denom in test explicitely if they are using money - so it is obviously to read, even if it is same for all tests and could be defaulted in suite).

[the remark this answers is not in the document]
Comment (ueco-jb) [reply packages/voting-contract/src/multitest/early_end.rs:38]: Obviously removed by mistake, since I added it everywhere else anyway.

File: packages/voting-contract/src/lib.rs (hunk 1 above)
Comment (ueco-jb) [reply packages/voting-contract/src/lib.rs:120]: Interesting.. 
https://github.com/CosmWasm/cosmwasm/blob/main/packages/std/src/traits.rs#L22
`Storage` description itself doesn't tell you anything about the cache.
I didn't know about it.

File: packages/voting-contract/src/lib.rs (hunk 3 above)
Comment (ueco-jb) [reply packages/voting-contract/src/lib.rs]: Agree.

**Comment by ueco-jb** [comment]
> This save doesn't write to the storage directly, but to a cache. All such changes are committed to persistent storage later if the fn succeeds and discarded if the fn returns an error. 

This still bothers me though. Because as I wrote in description:
> So someone tries to vote on proposal, update_status() changes state to Rejected and vote is rejected, but then validator queries the proposal and sees that status was the same as before.

I think this will be confusing and we should mitigate that.

**Comment by ueco-jb** [comment]
Anyway, PR solves problem from issue and works.

I referenced my problems in new issue, so this one could actually be merged.

File: packages/voting-contract/src/lib.rs [hunk 5]
```diff
@@ -197,18 +198,24 @@ where
...
+    prop.update_status(&env.block);
+
+    if [Status::Executed, Status::Passed]
         .iter()
         .any(|x| *x == prop.status)
     {
         return Err(ContractError::WrongCloseStatus {});
     }
-    if !prop.expires.is_expired(&env.block) {
+    if prop.status == Status::Open {
```
Comment (maurolacy) [inline packages/voting-contract/src/lib.rs:215]: I don't think this is right. This will allow closing `Pending` proposals that are not expired yet.

**Comment by uint** [comment]
> > So someone tries to vote on proposal, update_status() changes state to Rejected and vote is rejected, but then validator queries the proposal and sees that status was the same as before - probably just Open.
> 
> I think this will be confusing and we should mitigate that, but now I don't have any idea how. Wrong idea here - unless we start returning some empty response with error message in couple cases...?

Does this actually happen though? The status query doesn't check the storage directly, but uses a helper that's supposed to return the current status taking expiration into account:
https://github.com/confio/poe-contracts/blob/main/packages/voting-contract/src/lib.rs#L231

I think the idea with this stuff is that queries use `current_status()` and executions use `update_status()` and then everything checks out.

File: packages/voting-contract/src/state.rs [hunk 6]
```diff
@@ -47,6 +47,58 @@ impl<P> From<Proposal<P>> for ProposalInfo {
     }
 }
 
+impl<P> Proposal<P> {
```
Comment (maurolacy) [inline packages/voting-contract/src/state.rs:50]: I assume this was just moved and is unmodified.

**Review by maurolacy — COMMENTED** [review]
Looks good. Just some questions / comments, and what I think is an error when closing.

File: packages/voting-contract/src/state.rs (hunk 6 above)
Comment (ueco-jb) [reply packages/voting-contract/src/state.rs:50]: I explained that in description, it's just moved.

**Comment by ueco-jb** [comment]
> I think the idea with this stuff is that queries use current_status() and executions use update_status() and then everything checks out.

Yeah, you're right. I just realized, that despite status in memory not being correct, in the end it is correct for end user who uses query.
We "simply" must be carefull to make sure we use that helper everywhere.

File: packages/voting-contract/src/lib.rs [hunk 7]
```diff
@@ -116,12 +116,13 @@ where
 {
     // ensure proposal exists and can be voted on
     let mut prop = proposals().load(deps.storage, proposal_id)?;
-    if prop.status != Status::Open {
+    prop.update_status(&env.block);
+
+    if prop.status == Status::Rejected {
+        return Err(ContractError::Rejected {});
```
[the remark this answers is not in the document]
Comment (ueco-jb) [reply packages/voting-contract/src/lib.rs:122]: When I started implementing this and noticed that in-memory status won't be actually rejected, I thought that more explicit error might be more useful.
But okay, since query actually will show that as rejected I guess it's superflous.

File: packages/voting-contract/src/lib.rs [hunk 8]
```diff
@@ -197,18 +198,24 @@ where
...
 
-    let mut prop = proposals::<P>().load(deps.storage, proposal_id)?;
-    if [Status::Executed, Status::Rejected, Status::Passed]
+    let mut prop = proposals().load(deps.storage, proposal_id)?;
+
+    if prop.status == Status::Rejected {
+        return Err(ContractError::Rejected {});
+    }
+
+    prop.update_status(&env.block);
```
[the remark this answers is not in the document]
Comment (maurolacy) [reply packages/voting-contract/src/lib.rs:207]: > > I think the idea with this stuff is that queries use current_status() and executions use update_status() and then everything checks out.
> 
> Yeah, you're right. I just realized, that despite status in memory not being correct, in the end it is correct for end user who uses query. We "simply" must be carefull to make sure we use that helper everywhere.

Just wrote a variant of the same above.

**Comment by maurolacy** [comment]
> We "simply" must be carefull to make sure we use that helper everywhere.

I was just thinking that a (relatively cumbersome) way to do this would be to use two different structs, one for state with private members, and one for serialisation / deserialization with pub ones.

File: packages/voting-contract/src/lib.rs (hunk 5 above)
Comment (ueco-jb) [reply packages/voting-contract/src/lib.rs]: Okay, I reverted that change.
It's redundant to check expiration again since update status does that as well, but otherwise I'd have to create another 3 line iter with statuses `Pending` and `Open` as above, or just long if condition, which is tedious... and result is the same in the end.

File: packages/voting-contract/src/lib.rs [hunk 9]
```diff
@@ -116,12 +116,13 @@ where
 {
     // ensure proposal exists and can be voted on
     let mut prop = proposals().load(deps.storage, proposal_id)?;
-    if prop.status != Status::Open {
+    prop.update_status(&env.block);
+
+    if prop.status == Status::Rejected {
```
[the remark this answers is not in the document]
Comment (ueco-jb) [reply packages/voting-contract/src/lib.rs]: Agree. `update_status` now returns status as well.

**Comment by uint** [comment]
> > We "simply" must be carefull to make sure we use that helper everywhere.
> 
> I was just thinking that a (relatively cumbersome) way to do this would be to have / use two structs, one for state, with private members, and one for serialisation / deserialization, with pub ones.

Yeah, that's one way to do it. I opened an issue for this: https://github.com/confio/poe-contracts/issues/63

**Review by uint — APPROVED** [review]
LGTM

File: packages/voting-contract/src/lib.rs [hunk 10]
```diff
@@ -116,12 +116,10 @@ where
 {
     // ensure proposal exists and can be voted on
     let mut prop = proposals().load(deps.storage, proposal_id)?;
-    if prop.status != Status::Open {
+
+    if prop.update_status(&env.block) != Status::Open {
```
Comment (maurolacy) [inline packages/voting-contract/src/lib.rs:120]: After reading the (spot-on) comments about status not being committed on error, this is actually similar to just calling `current_status()`. So, there's really no need to modify `update_status` to return the updated status, and `current_status()` will work just as well here, as far as I can tell.

Sorry for the confusion.

File: packages/voting-contract/src/lib.rs (hunk 8 above)
[the remark this answers is not in the document]
Comment (maurolacy) [reply packages/voting-contract/src/lib.rs:204]: Same here. If the code errors below, this status update will be discarded. And if it does not, the status will be saved later, so, there's really no need to call `update_status` instead of `current_status`.

The bug is, not calling any of those, and reading the status directly.
